### ISSUE TITLE
Adding a requirements.txt

### ISSUE THREAD

**Issue by IcyArse** [AOSSIE-Org/EduAid#16]
It'll be helpful to add a requirements.txt to the repository for ease of life. Setting up multiple environments tend to be tedious and having base compatible library versions will be useful if any conflicting updates are introduced to them in future. As well prevent encountering errors in case you missed out on a library.

I have just started exploring open source collaborations, apologies if there are obvious reasons for the absence of requirements file.

**Comment by Raghucharan16** [comment]
Hey @IcyArse I would like to add requirements.txt file to the Repo. assign me this, and I'll go through the repo and add the file.
I also have worked on generating questions on given topic by fine tuning LLM. hope that may help in this project.

**Comment by IcyArse** [comment]
I already have a requirements file, I was rather looking for feed back from regular/managing contributors if we should push requirements file to the main repository.

**Comment by Raghucharan16** [comment]
@IcyArse yeah noted🙂
