### ISSUE TITLE
[improvement] Adding Context-Menu option for Generating Quiz

### ISSUE THREAD

**Issue by Roaster05** [AOSSIE-Org/EduAid#17]
### Description:

The integration of a **context-menu** feature for copied text streamlines the workflow by automating the insertion of text into the input box, eliminating the need for manual pasting. This enhancement optimizes user interaction and reduces friction, ultimately improving the efficiency of generating quizzes from browser text. Additionally, it enhances the overall usability of the application by providing a more intuitive and seamless experience for users.

### Expected Output:

Implementing a context menu feature that appears upon right-clicking a selected text, offering users the choice to input the text directly into the input text field within the extension's popup window. This enhancement streamlines user interaction by providing a convenient method for transferring highlighted text into the designated input field within the extension interface.

**Comment by shrutibhardwaj22** [comment]
I would like to work on this issue. Can you please assign it to me?"
