### ISSUE TITLE
Feat: Multiple-Choice Question Generation

### ISSUE THREAD

**Issue by Aditya062003** [AOSSIE-Org/EduAid#20]
### Description
Currently, our platform lacks the ability for users to generate multiple-choice questions (MCQs) for their content. This feature would greatly enhance the usability and educational value of our platform by allowing users to create quizzes and assessments more efficiently.

### Proposed Solution
I propose implementing a feature that enables users to generate MCQs based on their content.

### Expected Behavior
- Users should be able to select content from their resources.
- The system should generate multiple-choice questions based on the provided content.
- Generated MCQs should be displayed to users for review and can they can be saved for future references.

### Additional Information
- Are there any existing tools or libraries that could be integrated for this purpose?
- What would be the ideal workflow for users to utilize this feature?
- Any potential challenges or considerations to keep in mind during development?

### Labels
- enhancement
- feature request

**Comment by MJakash** [comment]
Hey @Aditya062003, I would like to work on this issue. It would be grateful if you could assign me this issue.
