### ISSUE TITLE
Feat: Integration of OpenAI API for QA Pair Generation

### ISSUE THREAD

**Issue by Aditya062003** [AOSSIE-Org/EduAid#24]
### Description
Currently, our system generates QA pairs using local models, which may have limitations due to computational constraints. To enhance the quality and diversity of generated QA pairs, I propose integrating the OpenAI API to allow users to utilize their own API keys and access OpenAI models for QA pair generation.

### Proposed Solution
- Integrate OpenAI API functionality into our system.
- Provide a mechanism for users to input their OpenAI API key.
- Develop a workflow to facilitate QA pair generation using OpenAI models.
- Ensure compatibility and security measures for handling user API keys.

### Expected Benefits
- Enhanced quality and diversity of generated QA pairs.
- Access to advanced models and capabilities not feasible on local machines.
- Improved user experience and satisfaction.

### Additional Information
- Considerations for API rate limits and usage costs.
- Compatibility with existing features and workflows.
- Potential collaboration opportunities with OpenAI.

### Labels
- enhancement
- feature request

**Comment by salmoneatenbybear** [comment]
Hi, I am Aditya Singh, a third year B.Tech Artificial Intelligence student... I find this idea really interesting and would be extremely grateful to get to work on this, i have already started to do so... will update soon, if this issue can be assigned to me, it would be terrific !
