### ISSUE TITLE
Creating a Quiz Website

### ISSUE THREAD

**Issue by Imamul5641** [AOSSIE-Org/EduAid#26]
**Description:**
Currently, our quiz system relies solely on the browser extension, which has limitations in storing scores and handling interruptions caused by browser behavior.

**Issue:**
Presenting quizzes as pop-up pages poses challenges as accidental clicks outside the window can disrupt the quiz-taking process.

**Comment by Anshukumar8529** [comment]
To overcome these limitations, a more robust solution is required, such as implementing a client-side database like IndexedDB for data storage and handling interruptions. By saving user data periodically, you can ensure that progress is not lost during interruptions. Additionally, syncing user data with a server-side database can help recover progress even after browser updates or restarts.

**Comment by coderwithsense** [comment]
You can list ideas, i can make them

**Comment by MuktiMishra** [comment]
I can work on this..
