### ISSUE TITLE
[Improvement] Leveraging SidePanel API for better Visualisation of Quiz.

### ISSUE THREAD

**Issue by Roaster05** [AOSSIE-Org/EduAid#29]
### Description:
The current visualization of generated questions is limited within a modal present in the extension's Popup. However, this setup becomes cumbersome when dealing with more than two questions, as it becomes challenging to distinguish between them clearly. Therefore, there's a pressing need for an enhanced visualization method that can effectively handle multiple questions. This enhancement can be achieved by leveraging the **SidePanel's API** recently introduced in the **Chrome Extension.**

### Expected Output:
The proposed solution involves the implementation of a dedicated sidePanel page to display the questions generated by the Model. Unlike the current setup, where questions are displayed within a modal, the sidePanel page will present questions in a vertical orientation. This layout allows for better organization and readability, especially when dealing with multiple questions. Additionally, the sidePanel page will retain all functionalities currently offered by the `question_generation.html` page, ensuring a seamless user experience. Overall, this enhancement aims to improve the usability and aesthetics of the quiz visualization process within the extension.

**Comment by coderwithsense** [comment]
I can work on this one.
