### ISSUE TITLE
Text Area Overflow Issue

### ISSUE THREAD

**Issue by Aditya062003** [AOSSIE-Org/EduAid#3]
The text area in the extension was exceeding its designated area, causing an overflow and negatively impacting the user experience. Users were unable to view and interact with the full content within the text area, leading to confusion.

## Before :

<img src="https://github.com/AOSSIE-Org/EduAid/assets/102402625/96fda98b-47b2-4eb7-b3fb-ba78dd9842f1" width="400" height="400" alt = "Before1ss"/>

<img src="https://github.com/AOSSIE-Org/EduAid/assets/102402625/d06b1fb4-6df2-49bc-aa80-9b4ca423f200"  height ="400" width="400" alt = "Before12s" />

## After :
<img src="https://github.com/AOSSIE-Org/EduAid/assets/102402625/f86c08e6-2fcc-4380-b7d2-ce579cabebab"  height ="400" width="400" alt = "After1ss"/>

**Comment by Arjun20X** [comment]
i would like to work on this issue. Please assign this to me

**Comment by sakina1303** [comment]
I'll be able to work on this. Could you please assign me to the task? Thanks in advance!

**Comment by 11yashiagrawal** [comment]
Hi, I wouls like to work on this issue, kindly assign it to me @Aditya062003
