### ISSUE TITLE
[Improvement] Customisation in Generated Quiz

### ISSUE THREAD

**Issue by Roaster05** [AOSSIE-Org/EduAid#38]
### Current State:

Currently, our extension provides a view button that allows users to see the generated quiz. However, the generated questions may not always meet the user's expectations due to limitations in the Question Generation Model. Unfortunately, once the questions are generated, there's no provision for modifying them to better suit the user's needs. This lack of flexibility prevents users from adjusting the generated questions to cover the desired scope or address specific requirements.

### Proposed Solution:

To address this issue, we propose implementing features for modifying, deleting, and adding Question-Answer pairs in the generated set of questions. By providing users with the ability to edit the generated questions, they can ensure that the quiz adequately covers the desired scope according to their perspective. This mechanism acts as a last layer of verification, allowing users to make necessary changes or adjustments without the need to rerun the Question Generation Model. Ultimately, this enhancement will improve user satisfaction and increase the utility of our extension by offering more control and customization over the generated quizzes.

**Comment by Saahil-Kapoor** [comment]
Hello , is this issue still open , i would like to contribute to this

**Comment by Deepanshu9376** [comment]
Hi @Roaster05 I can implement the proposed solution, could you please assign me this issue?

**Comment by shrutibhardwaj22** [comment]
I am interested in working on this issue. Could you kindly assign it to me?
