### ISSUE TITLE
Implementing frontend for the extension

### ISSUE THREAD

**Issue by keshav-nischal** [AOSSIE-Org/EduAid#5]
Enhancement Proposal: Rejuvenate Extension Frontend

Current State:

The current frontend design of the extension feels outdated and lacks visual appeal.

Proposed Solution:

This proposal suggests implementing a pre-designed frontend based on design #2 .

Action Items:

    Assign this issue to me for implementation.
    Provide access to design document #2 for reference.

Further Discussion:

This proposal welcomes further discussion and collaboration

**Comment by faresh9** [comment]
**_I'm interested in working this issue too_**

**Comment by HarshSandhu1111** [comment]
@keshav-nischal  Assign this issue to me for implementation.

**Comment by nishant1194** [comment]
Hey! I want to work on this issue. Please assign it to me..
