### ISSUE TITLE
Suggestion: Revamp Button Design on Landing Page for Improved User Experience

### ISSUE THREAD

**Issue by SinghaAnirban005** [AOSSIE-Org/EduAid#56]
I would like to propose a redesign of the buttons on the landing page to enhance the overall user experience. 
The current button design feels a bit dated and could benefit from a more modern, visually appealing style.

Original landing page buttons
![Screenshot 2024-10-24 193654](https://github.com/user-attachments/assets/c5a44cb5-123b-45bc-af03-128ed8d19047)

Revamped Landing page buttons ..

https://github.com/user-attachments/assets/bc0aba6f-5b51-4b92-a21c-9a7f953057d7

**Comment by SinghaAnirban005** [comment]
Refer to PR #57

**Comment by krishkishore972** [comment]
hey ! assign me the issue i will start working on it
