### ISSUE TITLE
bug report 🐛: Outdated version of packages in `requirements.txt`

### ISSUE THREAD

**Issue by Tuhinm2002** [AOSSIE-Org/EduAid#58]
![Screenshot (13)](https://github.com/user-attachments/assets/05a7c414-476e-4437-9965-07c58c4fa787)

** Bug

In `requirements.txt` file the versions provided for the packages are now unsupported when trying to install it locally. 

Caused due to outdated version of `torch` module and `en-core-web-sm` module

This needs to be fixed

** Reproduce the bug
``` pip install -r requirements.txt ```

**Comment by Tuhinm2002** [comment]
@Aditya062003 please see these minor changes and approve the request here #59

**Comment by Aditya062003** [comment]
Hey @Tuhinm2002, Thanks for your PR! I find it is good to pin a version on some core dependencies to avoid any case of incompatible versions. I'm open to exploring reduced version specificity for some packages, but would prefer to continue to pin versions for the primary dependencies.
