### ISSUE TITLE
Extension Not Working in the Background

### ISSUE THREAD

**Issue by faresh9** [AOSSIE-Org/EduAid#6]
## Description

The extension currently does not maintain functionality in the background. When the extension popup is closed, it appears to terminate, resulting in the discontinuation of background processes.

## Steps to Reproduce

1. Open the extension popup.
2. Perform actions that trigger background functionality.
3. Close the extension popup.
4. Observe that background functionality stops.

## Expected Behavior

The extension should continue running in the background in the generating questions phase.

**Comment by AviGawande** [comment]
@prarabdhshukla need your help for setting up the project locally and getting it on the browser,if any documentation is available..
