### ISSUE TITLE
[Feature] Implement "Generate Quiz from Selected Text" Context Menu Feature

### ISSUE THREAD

**Issue by yatikakain** [AOSSIE-Org/EduAid#60]
## Description
Add a new context menu item labeled "Generate Quiz from Selected Text" that allows users to generate quizzes based on highlighted text from any webpage.

## Feature Details
1. **Context Menu Integration:** When a user selects text on a webpage and right-clicks, they should see a new option in the context menu—"Generate Quiz from Selected Text."
2. **Extension Prompt and Auto-Fill:** Upon selecting this option, the extension logo should be highlighted, capturing the selected text as the context for quiz generation.
3. **Service Worker Utilization:** Implement a service worker to handle background processes, such as managing context menu events and ensuring seamless communication between the webpage and the extension.

## Expected Behavior
- The "Generate Quiz from Selected Text" option should appear in the context menu on any webpage when text is highlighted.
- Selecting this option should open the extension, with the highlighted text pre-filled as the basis for generating a quiz.
- The service worker should efficiently manage the context menu functionality, allowing for responsive interactions and improved performance.

## Additional Context
This feature would streamline the quiz creation process, making it easier for users to generate quizzes directly from the content they're viewing. Utilizing a service worker will enhance the extension's capability to handle background tasks without interfering with the main thread, ensuring a smoother user experience.

## Proposed Solution
Implement the context menu option using JavaScript’s `chrome.contextMenus` API to detect selected text and trigger the extension’s quiz generation process. The service worker will facilitate the context menu interactions and handle data processing as needed.

Would love to take this on if it aligns with the project's direction! Please let me know if I can be assigned this task.

**Comment by yatikakain** [comment]
@Aditya062003 Can you please review this and assign it to me.

**Comment by Aditya062003** [comment]
I’ve assigned this issue to you.
