### ISSUE TITLE
[Feature]: Content Overflow Issue on /question_type Page 

### ISSUE THREAD

**Issue by PruthviGBhat** [AOSSIE-Org/EduAid#65]
**Description**: On the /question_type page, the content is overflowing beyond the visible viewport, causing layout issues on both mobile and desktop devices. The background does not cover the full screen, and elements are not properly contained within the viewport

** Current Behaviour**
![Screenshot 2024-11-11 171102](https://github.com/user-attachments/assets/5b9edf2f-8908-40fe-9957-a5da108ff94f)

**What is Happening** :
1 )content overflow from the screen size
2) Not responsive in mobile devices

**Expected Behaviour**
![Screenshot 2024-11-11 185906](https://github.com/user-attachments/assets/485aacb5-25c1-4f67-9684-86d468efd125)

**Comment by PruthviGBhat** [comment]
[https://github.com/AOSSIE-Org/EduAid/pull/66](url)

This solves the #65 issue

**Comment by PruthviGBhat** [comment]
**https://github.com/AOSSIE-Org/EduAid/pull/66**  (Pull request)    
This pull request solves the issue #65

**Comment by mayankdhangar2408** [comment]
hey @PruthviGBhat , is this issue has been solved already ??

**Comment by PruthviGBhat** [comment]
Hey @mayankdhangar2408, Yes, It has been solved

@maintainer please review this code

**Comment by mayankdhangar2408** [comment]
@PruthviGBhat okk thanks for confirming, if you know some other issues than assign them to me

**Comment by chetansharma0706** [comment]
is this issue resolved finally? or anyone is currently working on??

**Comment by Nitish2626** [comment]
This issue is not fixed yet i am working on it.
