### ISSUE TITLE
Revamp the UI for the EduAid Web App

### ISSUE THREAD

**Issue by 0xsambit** [AOSSIE-Org/EduAid#71]
We need to revamp the UI of the EduAid web app to improve its usability and visual appeal. Here are the specific areas that require attention:

- **Overall Design**: Modernize the overall look and feel of the application to make it more appealing and user-friendly.
- **Navigation**: Improve the navigation structure to ensure users can easily find and access different features and sections of the app.
- **Responsiveness**: Enhance the responsiveness of the application to ensure it works well on all devices, including desktops, tablets, and mobile phones.
- **UI Elements**: Update the design of forms, buttons, and other UI elements to make them more intuitive and visually consistent.
- **Accessibility**: Ensure that the new design is accessible to all users, including those with disabilities. This includes proper color contrast, keyboard navigation, and screen reader support.
- **Consistency**: Maintain a consistent design language throughout the application, adhering to modern web design trends and best practices.

## I would like to start working in this as soon as possible

**Comment by 0xsambit** [comment]
Sure .. I am making one figma design.

**Comment by 0xsambit** [comment]
@Aditya062003 Here is one minimalist Figma design. I will make similar to this with the required changes

https://www.figma.com/design/DbWM5ONeXxkhLEzGal6Vo6/EduAid?node-id=0-1&t=pn1JduB7UDCspIYe-1

**Comment by 0xsambit** [comment]
@Aditya062003 Can I start working on it.  I need to be assigned the issue

**Comment by Aditya062003** [comment]
Please follow the standard issue template.

**Comment by 0xsambit** [comment]
@Aditya062003 What is standard issue template. There is no issue template showing up.
