### ISSUE TITLE
Creating a better looking footer 

### ISSUE THREAD

**Issue by ritwik-69** [AOSSIE-Org/EduAid#72]
Currently the footer of the web app is blank and can be improved to look much better. 

Current look:
![image](https://github.com/user-attachments/assets/0538f680-2c40-464f-a5be-5b129a9ee3d7)

I would like to start working in this as soon as possible

**Comment by anya-xcode** [comment]
Hi Ritwik,  
I think I'll be able to work on this. Could you please assign me to the task? 
Thanks.

**Comment by ritwik-69** [comment]
@anya-xcode Hi I am currently working on this.

**Comment by Aditya062003** [comment]
This issue is already being addressed here: AOSSIE-Org/EduAid#65. Therefore, closing this one.
