### ISSUE TITLE
[Improvement] Make Pages Responsive and Improving UI

### ISSUE THREAD

**Issue by dmelloaries** [AOSSIE-Org/EduAid#75]
Currently, the pages components are not optimized for mobile UI, resulting in poor responsiveness and an inconsistent layout. Additionally, the UI appears shaky on various desktop screens, which negatively impacts the user experience.

Current UI Issues:
- Lack of mobile responsiveness.
- UI misalignment and jitter on desktop screens.

https://github.com/user-attachments/assets/8beea332-b41f-4655-9db7-397b34920faf

**Comment by dmelloaries** [comment]
I would like to work on fixing this issue. Could you please assign it to me?

**Comment by Aditya062003** [comment]
Hey @dmelloaries , A similar issue already exists, pls check this https://github.com/AOSSIE-Org/EduAid/issues/65
